### PR TITLE
can't build

### PR DESCRIPTION
**Pull request by SkiddedMC**
'''Downloading https://services.gradle.org/distributions/gradle-6.9.1-all.zip
..............10%..............20%...............30%..............40%..............50%...............60%..............70%..............80%...............90%..............100%

Welcome to Gradle 6.9.1!

Here are the highlights of this release:
 - This is a small backport release.
 - Java 16 can be used to compile when used with Java toolchains
 - Dynamic versions can be used within plugin declarations
 - Native support for Apple Silicon processors

For more details see https://docs.gradle.org/6.9.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/FDPClientChina/FDPClientChina/build.gradle' line: 6

* What went wrong:
Plugin [id: 'net.minecraftforge.gradle.forge', artifact: 'com.github.asbyth:ForgeGradle:ddb1eb0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.asbyth:ForgeGradle:ddb1eb0')
  Searched in the following repositories:
    MavenRepo
    Gradle Central Plugin Repository
    maven(https://maven.minecraftforge.net/)
    maven2(https://jitpack.io/)
    maven3(https://repo.spongepowered.org/repository/maven-public/)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 9s
Error: Process completed with exit code 1.'''

### CODE REVIEW

**Comment by rezaebi** [comment]
use java 1.8 then and config gradle manual , also use vpn to see if fixed

**Comment by DinoFengz** [comment]
because u r using a ass client xd

**Comment by kotonemywaifu** [comment]
> because u r using a ass client xd

shut up kid you can only copy and paste

**Comment by Wlenk** [comment]
cnm辱华狗

**Pull request closed without merging**
